language: android
android:
  components:
    - platform-tools
    - build-tools-21.1.1
    - android-21
    - sys-img-x86-android-21
    - sys-img-armeabi-v7a-android-21
    - extra
before_install: "chmod +x gradlew"