language: android
android:
  components:
  - platform-tools
  - build-tools-21.1.1
  - android-21
  - sys-img-x86-android-21
  - sys-img-armeabi-v7a-android-21
  - extra
before_install:
- chmod +x gradlew
- "./gradlew -v"
- uname -a
script:
- "./gradlew clean test"
jdk:
- oraclejdk7
env:
  matrix:
  - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a
  global:
    secure: aJf/vu0fre/ji2DO4RYrAwbVfA2kLh3/mSmXPtgRToqjX3eLyVsHxPipU4IXW/LjtdkUa3Ag/pvn+UyvtJFpCWmNtkBXIU0SexLk6mn/3+gFqVP+uS0nvTBR8OB+5uLLWjKtLLrixnZio7H67DZ3CR0F2SZpIS0duWsns6NFRvI=
after_success:
- "./gradlew jacocoTestReport coveralls"
- "./clone-gh-pages.sh"
- rm -rf gh-pages/reports
- cp -r ./app/build/reports ./gh-pages
- mv gh-pages/reports/jacoco/.resources gh-pages/reports/jacoco/resources
- find gh-pages/reports/jacoco -type f -exec sed -i 's/.resources/resources/g' {} +
- mv gh-pages/reports/jacoco/.sessions.html gh-pages/reports/jacoco/sessions.html
- find gh-pages/reports/jacoco -type f -exec sed -i 's/.sessions/sessions/g' {} +
- ./gradlew lint . --html gh-pages/reports/index.html
- "./update-gh-pages.sh"
