language: android
android:
  components:
    - platform-tools
    - build-tools-21.1.1
    - android-21
    - sys-img-x86-android-21
    - sys-img-armeabi-v7a-android-21
    - extra
before_install:
    - chmod +x gradlew
    # for gradle output style
    # - export TERM=dumb

    # environment info
    - ./gradlew -v
    - uname -a
# Let's try to build...
script:
    - ./gradlew clean test