language: android
android:
  components:
    - platform-tools
    - build-tools-21.1.1
    - android-21
    - sys-img-x86-android-21
    - sys-img-armeabi-v7a-android-21
    - extra
before_install:
    - chmod +x gradlew
    # for gradle output style
    - export TERM=dumb

    # environment info
    - ./gradlew -v
    - uname -a
after_script:
    - gradle check
    - ./gradlew :app:assembleDebug
    - ./gradlew :app:assembleDebugUnitTest
# Let's try to build...
script: ./gradlew clean build